default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: socialmap_development
test:
  <<: *default
  database: socialmap_test
production:
  <<: *default
  database: socialmap_production
  username: socialmap
  password: <%= ENV['SOCIALMAP_DATABASE_PASSWORD'] %>
